// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

# The currency APIs help you retrieve exchange rates and convert prices between currencies easily.
public isolated client class Client {
    final http:Client clientEp;
    final readonly & ApiKeysConfig apiKeyConfig;
    # Gets invoked to initialize the `connector`.
    #
    # + apiKeyConfig - API keys for authorization 
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ApiKeysConfig apiKeyConfig, ConnectionConfig config =  {}, string serviceUrl = "https://api.cloudmersive.com/currency/exchange-rates") returns error? {
        http:ClientConfiguration httpClientConfig = {httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
        self.apiKeyConfig = apiKeyConfig.cloneReadOnly();
    }

    # Get a list of available currencies and corresponding countries
    #
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function listAvailableCurrencies(map<string|string[]> headers = {}) returns AvailableCurrencyResponse|error {
        string resourcePath = string `/list-available`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Converts a price from the source currency into the destination currency
    #
    # + 'source - Source currency three-digit code (ISO 4217), e.g. USD, EUR, etc
    # + destination - Destination currency three-digit code (ISO 4217), e.g. USD, EUR, etc
    # + headers - Headers to be sent with the request 
    # + payload - Input price, such as 19.99 in source currency 
    # + return - OK 
    remote isolated function convertCurrency(string 'source, string destination, decimal payload, map<string|string[]> headers = {}) returns ConvertedCurrencyResult|error {
        string resourcePath = string `/convert/${getEncodedUri('source)}/to/${getEncodedUri(destination)}`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Gets the exchange rate from the source currency into the destination currency
    #
    # + 'source - Source currency three-digit code (ISO 4217), e.g. USD, EUR, etc
    # + destination - Destination currency three-digit code (ISO 4217), e.g. USD, EUR, etc
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function getExchangeRate(string 'source, string destination, map<string|string[]> headers = {}) returns ExchangeRateResult|error {
        string resourcePath = string `/get/${getEncodedUri('source)}/to/${getEncodedUri(destination)}`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }
}
