// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

# Details of a specific currency
public type AvailableCurrency record {
    # Three-letter ISO 3166-1 country code
    @jsondata:Name {value: "CountryThreeLetterCode"}
    string countryThreeLetterCode?;
    # ISO 4217 currency three-letter code associated with the country
    @jsondata:Name {value: "ISOCurrencyCode"}
    string iSOCurrencyCode?;
    # Name of the country
    @jsondata:Name {value: "CountryName"}
    string countryName?;
    # Full name of the currency
    @jsondata:Name {value: "CurrencyEnglishName"}
    string currencyEnglishName?;
    # Symbol associated with the currency
    @jsondata:Name {value: "CurrencySymbol"}
    string currencySymbol?;
    # True if this country is currently a member of the European Union (EU), false otherwise
    @jsondata:Name {value: "IsEuropeanUnionMember"}
    boolean isEuropeanUnionMember?;
    # Two-letter ISO 3166-1 country code
    @jsondata:Name {value: "CountryISOTwoLetterCode"}
    string countryISOTwoLetterCode?;
};

# Result of performing an enumerate currencies operation
public type AvailableCurrencyResponse record {
    # List of available currencies from the API
    @jsondata:Name {value: "Currencies"}
    AvailableCurrency[] currencies?;
};

# Result of performing a get exchange rate operation
public type ExchangeRateResult record {
    # The exchange rate from the source to the destination currency
    @jsondata:Name {value: "ExchangeRate"}
    decimal exchangeRate?;
};

# Provides API key configurations needed when communicating with a remote HTTP endpoint.
public type ApiKeysConfig record {|
    # API Key Authentication
    @display {label: "", kind: "password"}
    string apikey;
|};

# Result of performing a Convert Currency operation
public type ConvertedCurrencyResult record {
    # Formatted price in the destination currency as a string
    @jsondata:Name {value: "FormattedPriceAsString"}
    string formattedPriceAsString?;
    # ISO 4217 currency three-letter code of destination price
    @jsondata:Name {value: "ISOCurrencyCode"}
    string iSOCurrencyCode?;
    # The converted price in the destination currency
    @jsondata:Name {value: "ConvertedPrice"}
    decimal convertedPrice?;
    # Destination currency symbol
    @jsondata:Name {value: "CurrencySymbol"}
    string currencySymbol?;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};
